name: mvp2
version: '3.1'

services:
  db1:
    image: postgres
    container_name: mvp2_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mvp2db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
